#!/bin/bash

# Команда для вставки нового элемента (папки) в последовательность из названий папок

# Логика команды
# Если у меня папки называются: 1-a, 2-a, 3-a
# А мне нужно вставить папку 2-b тогда все последующие номера должны увеличиться на единицу: переименовать последующие папки
# Должно получиться: 1-a, 2-b, 3-a (вместо 2-a), 4-a (вместо 3-a)

# Синтаксис команды
# ins <<номер>имя папки> 


# Получить номер папки
number() {
    echo "$1" | grep -o -P '^\d+'
}

# Сравнить номера папок
is_le() {
    # возврат bool: меньше либо равно
    [[ -n "$2" && $1 -le $2 ]]
}

# Фильтр: равно или больше
filter_ge() {
    local input=($(cat))
    local first="${input[0]}"
    for el in "${input[@]}"; do
        if is_le $(number "$first") $(number "$el"); then
            echo "$el"
        fi
    done
}


# Переименовать папку
rename() {
    # Ссылка на переданный массив
    local -n ref=$1
    local index=$2 name=$3
    local old=$(number $name)
    local new=$(($old + 1))
    ref[$index]="${name/$old/$new}"
    mv "$name" "${name/$old/$new}"
}



# Проверка полученных параметров скрипта
if [[ $# -ne 1 || ! -d "$1" ]]; then
    echo "Укажите базовую папку для начала нумерации"
    exit 1
fi

# Получаю начальную папку для нумерации
first="$1"

# Исключаю из поиска папки . и ..
ignore=(-not -name "." -not -name "..")
# Исключаю из поиска начальную папку
ignore+=(-not -name "$first")
find_args=(-maxdepth 1 "${ignore[@]}")

# Создаю отсортированный массив из имен папок
iter=("$first")
iter+=($(find . "${find_args[@]}" -type d | sort -V | sed 's|.*/||'))

# Убираю папки, номер которых меньше номера начальной папки
arr=($(echo "${iter[@]}" | filter_ge | cat))


# Переименовываю папки
for ((i = 1; i < ${#arr[@]}; i++)); do
    prev=$(number "${arr[$(($i - 1))]}")
    next=$(number "${arr[$i]}")
    if [[ $prev -eq $next ]]; then
        rename arr $i "${arr[$i]}"
    else
        break
    fi
done

