#!/data/data/com.termux/files/usr/bin/env bash

# Команда для подключения vim к файлам с удаленного сервера
# Редактирование удаленных файлов локально

user="user2"
ip_serv="85.159.231.218"

# vim scp://user2@85.159.231.218//home/user2/test.txt
vim "scp://${user}@${ip_serv}//${1}"

